#ifndef CONFIG_H
#define CONFIG_H

//THE MAP INFO
#define BOARD_WIDTH  800
#define BOARD_HEIGHT 1200
#define SCORE_PANEL_HEIGHT 160
#define BLOCK_SIDE_LENGTH 80
#define ROW_COUNT (1200 - SCORE_PANEL_HEIGHT)/BLOCK_SIDE_LENGTH
#define COLUMN_COUNT 800/BLOCK_SIDE_LENGTH
//THE MOVE INFO
#define DROP_SPEED 1000


#endif // CONFIG_H
